### PR TITLE
1: doesn't fail if packages are missing manifest.ttl or packake.json

### LINKED ISSUE #1: Program fails if listed package doesn't have manifest.ttl
Example command: 
`barnard59-docs barnard59-protocols`

Expected outcome:
Doc generation should issue warning, but not fail. 
The message shall contain:
- name of failing package.
- reason for failing (unpublished package OR missing manifest.ttl)

### PR DESCRIPTION
**Pull request by magdasalatka**
Solves https://github.com/zazuko/barnard59-docs/issues/1

### CODE REVIEW

**Review by bergos — CHANGES_REQUESTED** [review]
Looks good so far, but I don't think this package should include the generated docs. Can you remove the `docs.md` file? Let's use a separate issue for that topic.

**Comment by tpluscode** [comment]
I also think that some code changes will violate `standard` code style

**Comment by bergos** [comment]
@tpluscode I think that's right. Because of the top-level await, it can't be total error free. @magdasalatka can you run [standard](https://www.npmjs.com/package/standard) and fix all errors that show up in lines you changed? I guess there should be two errors left in the end. The top-level await requires bigger changes, so I will fix them in a separate PR.

**Comment by magdasalatka** [comment]
@tpluscode @tpluscode What exactly do you have in mind?
I see exactly same errors for master, and this branch

`  /home/magdalena/zazuko/barnard59-docs/bin/barnard59-docs.js:17:16: Parsing error: Cannot use keyword 'await' outside an async function`
 ` /home/magdalena/zazuko/barnard59-docs/index.js:9:22: Parsing error: Cannot use keyword 'await' outside an async function`

**Comment by tpluscode** [comment]
Ah, so it actually fails completely to process the file because it not valid syntax (at least not the, um, standard which `standard` uses)

Forget it then I guess. @bergos will refactor the `awaits` and apply code style later

**Review by bergos — APPROVED** [review]

**Pull request merged**
